### ISSUE TITLE
Doesn't work like intended :-(

### ISSUE THREAD

**Issue by GrafDogi** [sblask-webextensions/webextension-open-tabs-next-to-current#178]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

I linked Ctrl+Y to your extension.
Then I clicked a tab in the middle.
Then I pressed Ctrl+Y.
The new tab emerged after the most right tab. :-(

Did I forget something?

**Comment by sblask** [comment]
Works exactly like intended. Ctrl-Y is for opening a tab at the default location. Ctrl-T and opening tabs from a webpage will open tab next to the current.
