### ISSUE TITLE
Tabs are not properly ordered when re-opened in a window.

### ISSUE THREAD

**Issue by OnlyUsePascal** [sblask-webextensions/webextension-open-tabs-next-to-current#179]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome - Version 125.0.6422.141

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
**Summary**: When re-opening a window, the tabs are not correctly ordered. But there is a pattern of their in-correctness.

For instance, if I have a set of tabs like this, and I'm currently located at the asterisk-marked tab

```
(0)  (1)*  (2)  [tab group (3)  (4)]  (5)
```

If I re-open the window, the order of all tabs preserved `(5)` is moved next to `(1)`

```
(0)  (1)*  (5)  (2)  [tab group (3)  (4)]
```

If I re-open the window again, the tab group is now split, and `(4)` is moved next to `(1)`

```
(0)  (1)*  (4)  (5)  (2)  [tab group (3)]
```

Thank you very much for the extension!

**Comment by sblask** [comment]
There is no API for tab groups, so nothing can be done there.
