### ISSUE TITLE
Annoyingly creates new tabs at the beginning of the tab bar

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sblask-webextensions/webextension-open-tabs-next-to-current#181]
At least it does on my system.

When I right-click a link in a tab and select Open Link in New Tab, the link does in fact open next to the last tab as expected. That happens wherever the tab happens to be in the tabs list.

BUT, when I use ⌘+Tab to open a new tab, the tab always opens at the beginning of the tabs list on the left side next to the arrow instead of where it should, which is wherever the last tab was located in the visible tabs list. When that happens, the last tab is to the left of the new tab as it should be, but it's pushed off the list of visible tabs so that I must click the arrow to see it.

If I'm reading a tab in the middle of the visible tabs, ⌘+Tab SHOULD open a new tab next to it **AT THAT POSITION.** It should NOT shove the tab I was just looking at behind the left arrow and open up next to it. This extension is only supposed to open a new tab next to the open tab, not cause tabs to drastically change positions.

I didn't realize this extension is no longer maintained until I'd already typed my comment, but I'll post it anyway for anyone else experiencing the same frustrating issue. The extension shows it was updated on 6/14/24.

>sblask commented on Nov. 22, 2020
>I don't work on this extension anymore. 

### New Issue Checklist

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version

### What is your browser?

Firefox 155.18.0esr

### What is your extension version?

2.0.14

### What is your operating system?

macOS 10.14.6

**Comment by sblask** [comment]
There is nothing that can be done about the scrolling of the tab bar, there is no API for it.

**Comment by GitTheHellOutaHere** [comment]
Sorry, I hadn't noticed that this is already listed under **Known Issues** in the extension details.

So the two choices are: let Firefox create new tabs at the right side of the tab bar, or let this extension create tabs at the left side but adjacent to the last-used tab. I'm not sure one is better than the other, either way when the new tab is closed you return to the last-used tab and your tabs have shifted positions (if you have more than about 20 open in a window).

I think opening a new tab next to the current tab without changing tab position is something many users would appreciate. But I don't waste my time submitting suggestions to the almighty Mozilla, who knows what its users need better than they do themselves.

![Sarcasm - Big Bang Theory 1](https://github.com/user-attachments/assets/f88d1eb2-a5ca-45a6-830b-7c79aa41978b)
